name: mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  dotted_border: ^3.1.0
  image_picker: ^1.2.0
  provider: ^6.1.5+1
  http: ^1.5.0
  shared_preferences: ^2.5.3
  flutter_native_splash: ^2.4.6
  smooth_page_indicator: ^1.2.1
  google_sign_in: ^7.2.0
  flutter_facebook_auth: ^7.1.2
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.1
  flutter_web_auth_2: ^4.1.0
  uuid: ^4.5.1
  flutter_streaming_text_markdown: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/images/
